import * as React from 'react';
import Head from "next/head";
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import Box from '@mui/material/Box';
import { ThemeProvider, CssBaseline } from "@mui/material";
import { theme } from '../../utils/mainTheme';
import Footer from './Footer';

export default function Navigation(props) {
    const navbarColor = { backgroundColor: '#3a424f' };

    return (
        <ThemeProvider theme={theme}>
            <CssBaseline />

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppBar position="fixed" sx={{
                ...navbarColor,
                width: '100%',
            }}>
                <Toolbar sx={{
                    ...navbarColor,
                }}>
                    <img src='/nav-logo.png' alt='logo' width='40' height='40' />
                    <IconButton sx={{ marginLeft: 'auto' }}>
                        <MenuIcon sx={{ color: 'white' }} />
                    </IconButton>
                </Toolbar>
            </AppBar>
            <Box sx={{
                marginTop: '60px',
            }}>
                {
                    props.children
                }
            </Box>
            <Footer />
        </ThemeProvider>
    )
}