import Head from 'next/head'
import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import { mainFontStyle } from './_app';
import MenuIcon from '@mui/icons-material/Menu';
import { IconButton } from '@mui/material';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar sx={{
                backgroundColor: 'black',
                zIndex: 0,
                width: '100%'
            }}>
                <Toolbar sx={{ backgroundColor: 'black', }}>
                    <Typography className={mainFontStyle.className} sx={{
                        transform: 'rotate(-90deg)'
                    }}>
                        arch
                    </Typography>
                    <Typography className={mainFontStyle.className} variant="h4" >
                        N
                    </Typography>
                    <Typography className={mainFontStyle.className} variant="h4" sx={{
                    }}>
                        Ivanova
                    </Typography>
                    <IconButton sx={{ marginLeft: 'auto' }}>
                        <MenuIcon sx={{ color: 'white' }} />
                    </IconButton>
                </Toolbar>
            </AppBar>
        </>
    )
};